// @/config/cityMapConfig.ts - 도시별 지도 초기 설정

// 도시 크기 분류
export enum CitySize {
  SMALL = 'small', // 작은 도시/관광지 (예: 경주, 강릉, 전주)
  MEDIUM = 'medium', // 중간 규모 도시 (예: 부산, 대전, 인천)
  LARGE = 'large', // 대도시 (예: 서울, 도쿄, 뉴욕)
  EXTRA_LARGE = 'extra_large', // 메가시티/광역도시 (예: 로스앤젤레스, 하와이)
}

interface CityMapConfig {
  cityId: number;
  cityKo: string;
  cityEn: string;
  center: {
    lat: number;
    lng: number;
  };
  zoom: number;
  searchKeyword?: string; // 지오코딩 검색시 사용할 키워드
  size: CitySize; // 도시 크기 정보 추가
}

// 도시 크기별 기본 줌 레벨 설정
export const ZOOM_LEVELS = {
  [CitySize.SMALL]: 14, // 작은 도시는 더 자세히
  [CitySize.MEDIUM]: 12.5, // 중간 도시는 적당히
  [CitySize.LARGE]: 11, // 큰 도시는 넓게
  [CitySize.EXTRA_LARGE]: 10, // 메가시티는 매우 넓게
};

// 동적 줌 레벨 계산 함수
export function calculateDynamicZoom(cityConfig: CityMapConfig): number {
  return ZOOM_LEVELS[cityConfig.size] || ZOOM_LEVELS[CitySize.MEDIUM];
}

export const cityMapConfigs: Record<number, CityMapConfig> = {
  // 일본
  1: {
    cityId: 1,
    cityKo: '오사카',
    cityEn: 'OSAKA',
    center: { lat: 34.6937, lng: 135.5023 },
    zoom: 12,
    searchKeyword: 'Osaka, Japan',
    size: CitySize.MEDIUM,
  },
  2: {
    cityId: 2,
    cityKo: '도쿄',
    cityEn: 'TOKYO',
    center: { lat: 35.6762, lng: 139.6503 },
    zoom: 12,
    searchKeyword: 'Tokyo, Japan',
    size: CitySize.LARGE,
  },
  3: {
    cityId: 3,
    cityKo: '후쿠오카',
    cityEn: 'FUKUOKA',
    center: { lat: 33.5904, lng: 130.4017 },
    zoom: 12,
    searchKeyword: 'Fukuoka, Japan',
    size: CitySize.MEDIUM,
  },

  // 한국
  4: {
    cityId: 4,
    cityKo: '제주',
    cityEn: 'JEJU',
    center: { lat: 33.4996, lng: 126.5312 },
    zoom: 11,
    searchKeyword: 'Jeju Island, South Korea',
    size: CitySize.LARGE,
  },
  5: {
    cityId: 5,
    cityKo: '부산',
    cityEn: 'BUSAN',
    center: { lat: 35.1796, lng: 129.0756 },
    zoom: 12,
    searchKeyword: 'Busan, South Korea',
    size: CitySize.MEDIUM,
  },
  6: {
    cityId: 6,
    cityKo: '서울',
    cityEn: 'SEOUL',
    center: { lat: 37.5665, lng: 126.978 },
    zoom: 12,
    searchKeyword: 'Seoul, South Korea',
    size: CitySize.LARGE,
  },
  8: {
    cityId: 8,
    cityKo: '경주',
    cityEn: 'GYEONGJU',
    center: { lat: 35.8562, lng: 129.2247 },
    zoom: 13,
    searchKeyword: 'Gyeongju, South Korea',
    size: CitySize.SMALL,
  },
  10: {
    cityId: 10,
    cityKo: '강릉',
    cityEn: 'GANGNEUNG',
    center: { lat: 37.7519, lng: 128.8761 },
    zoom: 13,
    searchKeyword: 'Gangneung, South Korea',
    size: CitySize.SMALL,
  },
  13: {
    cityId: 13,
    cityKo: '여수',
    cityEn: 'YEOSU',
    center: { lat: 34.7604, lng: 127.6622 },
    zoom: 13,
    searchKeyword: 'Yeosu, South Korea',
    size: CitySize.MEDIUM,
  },
  18: {
    cityId: 18,
    cityKo: '거제통영',
    cityEn: 'GEOJETONGYEONG',
    center: { lat: 34.8808, lng: 128.6214 },
    zoom: 12,
    searchKeyword: 'Geoje, South Korea',
    size: CitySize.SMALL,
  },
  23: {
    cityId: 23,
    cityKo: '전주',
    cityEn: 'JEONJU',
    center: { lat: 35.8242, lng: 127.148 },
    zoom: 13,
    searchKeyword: 'Jeonju, South Korea',
    size: CitySize.SMALL,
  },
  24: {
    cityId: 24,
    cityKo: '남원',
    cityEn: 'NAMWON',
    center: { lat: 35.4164, lng: 127.3903 },
    zoom: 13,
    searchKeyword: 'Namwon, South Korea',
    size: CitySize.SMALL,
  },
  29: {
    cityId: 29,
    cityKo: '포항',
    cityEn: 'POHANG',
    center: { lat: 36.019, lng: 129.3435 },
    zoom: 12,
    searchKeyword: 'Pohang, South Korea',
    size: CitySize.MEDIUM,
  },
  30: {
    cityId: 30,
    cityKo: '대전',
    cityEn: 'DAEJEON',
    center: { lat: 36.3504, lng: 127.3845 },
    zoom: 12,
    searchKeyword: 'Daejeon, South Korea',
    size: CitySize.MEDIUM,
  },
  34: {
    cityId: 34,
    cityKo: '인천',
    cityEn: 'INCHEON',
    center: { lat: 37.4563, lng: 126.7052 },
    zoom: 12,
    searchKeyword: 'Incheon, South Korea',
    size: CitySize.MEDIUM,
  },
  35: {
    cityId: 35,
    cityKo: '춘천',
    cityEn: 'CHUNCHEON',
    center: { lat: 37.8813, lng: 127.7298 },
    zoom: 13,
    searchKeyword: 'Chuncheon, South Korea',
    size: CitySize.SMALL,
  },
  40: {
    cityId: 40,
    cityKo: '군산',
    cityEn: 'GUNSAN',
    center: { lat: 35.9676, lng: 126.7372 },
    zoom: 13,
    searchKeyword: 'Gunsan, South Korea',
    size: CitySize.MEDIUM,
  },
  42: {
    cityId: 42,
    cityKo: '목포',
    cityEn: 'MOKPO',
    center: { lat: 34.8118, lng: 126.3922 },
    zoom: 13,
    searchKeyword: 'Mokpo, South Korea',
    size: CitySize.MEDIUM,
  },
  49: {
    cityId: 49,
    cityKo: '안동',
    cityEn: 'ANDONG',
    center: { lat: 36.5684, lng: 128.7294 },
    zoom: 13,
    searchKeyword: 'Andong, South Korea',
    size: CitySize.SMALL,
  },
  52: {
    cityId: 52,
    cityKo: '울릉도',
    cityEn: 'ULLEUNG',
    center: { lat: 37.4844, lng: 130.9057 },
    zoom: 12,
    searchKeyword: 'Ulleungdo, South Korea',
    size: CitySize.SMALL,
  },
  56: {
    cityId: 56,
    cityKo: '가평',
    cityEn: 'GAPYEONG',
    center: { lat: 37.8316, lng: 127.5109 },
    zoom: 13,
    searchKeyword: 'Gapyeong, South Korea',
    size: CitySize.SMALL,
  },
  59: {
    cityId: 59,
    cityKo: '제천',
    cityEn: 'JECHEON',
    center: { lat: 37.1326, lng: 128.1911 },
    zoom: 13,
    searchKeyword: 'Jecheon, South Korea',
    size: CitySize.SMALL,
  },
  60: {
    cityId: 60,
    cityKo: '수원',
    cityEn: 'SUWON',
    center: { lat: 37.2636, lng: 127.0286 },
    zoom: 13,
    searchKeyword: 'Suwon, South Korea',
    size: CitySize.MEDIUM,
  },
  78: {
    cityId: 78,
    cityKo: '영월',
    cityEn: 'YEONGWOL',
    center: { lat: 37.1836, lng: 128.4617 },
    zoom: 13,
    searchKeyword: 'Yeongwol, South Korea',
    size: CitySize.SMALL,
  },

  // 유럽
  7: {
    cityId: 7,
    cityKo: '파리',
    cityEn: 'PARIS',
    center: { lat: 48.8566, lng: 2.3522 },
    zoom: 12,
    searchKeyword: 'Paris, France',
    size: CitySize.MEDIUM,
  },
  9: {
    cityId: 9,
    cityKo: '런던',
    cityEn: 'LONDON',
    center: { lat: 51.5074, lng: -0.1278 },
    zoom: 12,
    searchKeyword: 'London, United Kingdom',
    size: CitySize.EXTRA_LARGE,
  },
  17: {
    cityId: 17,
    cityKo: '바르셀로나',
    cityEn: 'BARCELONA',
    center: { lat: 41.3851, lng: 2.1734 },
    zoom: 12,
    searchKeyword: 'Barcelona, Spain',
    size: CitySize.MEDIUM,
  },
  19: {
    cityId: 19,
    cityKo: '로마',
    cityEn: 'ROMA',
    center: { lat: 41.9028, lng: 12.4964 },
    zoom: 12,
    searchKeyword: 'Rome, Italy',
    size: CitySize.MEDIUM,
  },
  28: {
    cityId: 28,
    cityKo: '프라하',
    cityEn: 'PRAHA',
    center: { lat: 50.0755, lng: 14.4378 },
    zoom: 12,
    searchKeyword: 'Prague, Czech Republic',
    size: CitySize.MEDIUM,
  },
  31: {
    cityId: 31,
    cityKo: '마드리드',
    cityEn: 'MADRID',
    center: { lat: 40.4168, lng: -3.7038 },
    zoom: 12,
    searchKeyword: 'Madrid, Spain',
    size: CitySize.MEDIUM,
  },
  32: {
    cityId: 32,
    cityKo: '빈',
    cityEn: 'WIEN',
    center: { lat: 48.2082, lng: 16.3738 },
    zoom: 12,
    searchKeyword: 'Vienna, Austria',
    size: CitySize.MEDIUM,
  },
  33: {
    cityId: 33,
    cityKo: '피렌체',
    cityEn: 'FIRENZE',
    center: { lat: 43.7696, lng: 11.2558 },
    zoom: 13,
    searchKeyword: 'Florence, Italy',
    size: CitySize.MEDIUM,
  },
  39: {
    cityId: 39,
    cityKo: '인터라켄',
    cityEn: 'INTERLAKEN',
    center: { lat: 46.6863, lng: 7.8632 },
    zoom: 13,
    searchKeyword: 'Interlaken, Switzerland',
    size: CitySize.MEDIUM,
  },
  41: {
    cityId: 41,
    cityKo: '부다페스트',
    cityEn: 'BUDAPEST',
    center: { lat: 47.4979, lng: 19.0402 },
    zoom: 12,
    searchKeyword: 'Budapest, Hungary',
    size: CitySize.MEDIUM,
  },
  44: {
    cityId: 44,
    cityKo: '베니스',
    cityEn: 'VENICE',
    center: { lat: 45.4408, lng: 12.3155 },
    zoom: 13,
    searchKeyword: 'Venice, Italy',
    size: CitySize.MEDIUM,
  },
  45: {
    cityId: 45,
    cityKo: '밀라노',
    cityEn: 'MILANO',
    center: { lat: 45.4642, lng: 9.19 },
    zoom: 12,
    searchKeyword: 'Milan, Italy',
    size: CitySize.MEDIUM,
  },
  47: {
    cityId: 47,
    cityKo: '베를린',
    cityEn: 'BERLIN',
    center: { lat: 52.52, lng: 13.405 },
    zoom: 12,
    searchKeyword: 'Berlin, Germany',
    size: CitySize.MEDIUM,
  },
  51: {
    cityId: 51,
    cityKo: '프랑크푸르트',
    cityEn: 'FRANKFURT',
    center: { lat: 50.1109, lng: 8.6821 },
    zoom: 12,
    searchKeyword: 'Frankfurt, Germany',
    size: CitySize.MEDIUM,
  },
  53: {
    cityId: 53,
    cityKo: '뮌헨',
    cityEn: 'MUNICH',
    center: { lat: 48.1351, lng: 11.582 },
    zoom: 12,
    searchKeyword: 'Munich, Germany',
    size: CitySize.MEDIUM,
  },
  54: {
    cityId: 54,
    cityKo: '암스테르담',
    cityEn: 'AMSTERDAM',
    center: { lat: 52.3676, lng: 4.9041 },
    zoom: 12,
    searchKeyword: 'Amsterdam, Netherlands',
    size: CitySize.MEDIUM,
  },
  55: {
    cityId: 55,
    cityKo: '이스탄불',
    cityEn: 'ISTANBUL',
    center: { lat: 41.0082, lng: 28.9784 },
    zoom: 11,
    searchKeyword: 'Istanbul, Turkey',
    size: CitySize.MEDIUM,
  },
  58: {
    cityId: 58,
    cityKo: '잘츠부르크',
    cityEn: 'SALZBURG',
    center: { lat: 47.8095, lng: 13.055 },
    zoom: 13,
    searchKeyword: 'Salzburg, Austria',
    size: CitySize.MEDIUM,
  },
  63: {
    cityId: 63,
    cityKo: '리스본',
    cityEn: 'LISBON',
    center: { lat: 38.7223, lng: -9.1393 },
    zoom: 12,
    searchKeyword: 'Lisbon, Portugal',
    size: CitySize.MEDIUM,
  },
  64: {
    cityId: 64,
    cityKo: '취리히',
    cityEn: 'ZURICH',
    center: { lat: 47.3769, lng: 8.5417 },
    zoom: 12,
    searchKeyword: 'Zurich, Switzerland',
    size: CitySize.MEDIUM,
  },
  66: {
    cityId: 66,
    cityKo: '브뤼셀',
    cityEn: 'BRUSSEL',
    center: { lat: 50.8503, lng: 4.3517 },
    zoom: 12,
    searchKeyword: 'Brussels, Belgium',
    size: CitySize.MEDIUM,
  },
  70: {
    cityId: 70,
    cityKo: '니스',
    cityEn: 'NICE',
    center: { lat: 43.7102, lng: 7.262 },
    zoom: 12,
    searchKeyword: 'Nice, France',
    size: CitySize.MEDIUM,
  },
  71: {
    cityId: 71,
    cityKo: '코펜하겐',
    cityEn: 'COPENHAGEN',
    center: { lat: 55.6761, lng: 12.5683 },
    zoom: 12,
    searchKeyword: 'Copenhagen, Denmark',
    size: CitySize.MEDIUM,
  },
  73: {
    cityId: 73,
    cityKo: '베른',
    cityEn: 'BERN',
    center: { lat: 46.948, lng: 7.4474 },
    zoom: 13,
    searchKeyword: 'Bern, Switzerland',
    size: CitySize.MEDIUM,
  },
  74: {
    cityId: 74,
    cityKo: '나폴리',
    cityEn: 'NAPOLI',
    center: { lat: 40.8518, lng: 14.2681 },
    zoom: 12,
    searchKeyword: 'Naples, Italy',
    size: CitySize.MEDIUM,
  },
  75: {
    cityId: 75,
    cityKo: '아테네',
    cityEn: 'ATHENS',
    center: { lat: 37.9838, lng: 23.7275 },
    zoom: 12,
    searchKeyword: 'Athens, Greece',
    size: CitySize.MEDIUM,
  },
  77: {
    cityId: 77,
    cityKo: '모스크바',
    cityEn: 'MOSCOW',
    center: { lat: 55.7558, lng: 37.6173 },
    zoom: 11,
    searchKeyword: 'Moscow, Russia',
    size: CitySize.MEDIUM,
  },
  81: {
    cityId: 81,
    cityKo: '쾰른',
    cityEn: 'COLOGNE',
    center: { lat: 50.9375, lng: 6.9603 },
    zoom: 12,
    searchKeyword: 'Cologne, Germany',
    size: CitySize.MEDIUM,
  },
  82: {
    cityId: 82,
    cityKo: '제네바',
    cityEn: 'GENEVA',
    center: { lat: 46.2044, lng: 6.1432 },
    zoom: 12,
    searchKeyword: 'Geneva, Switzerland',
    size: CitySize.MEDIUM,
  },
  83: {
    cityId: 83,
    cityKo: '오슬로',
    cityEn: 'OSLO',
    center: { lat: 59.9139, lng: 10.7522 },
    zoom: 12,
    searchKeyword: 'Oslo, Norway',
    size: CitySize.MEDIUM,
  },
  84: {
    cityId: 84,
    cityKo: '헬싱키',
    cityEn: 'HELSINKI',
    center: { lat: 60.1699, lng: 24.9384 },
    zoom: 12,
    searchKeyword: 'Helsinki, Finland',
    size: CitySize.MEDIUM,
  },
  85: {
    cityId: 85,
    cityKo: '함부르크',
    cityEn: 'HAMBURG',
    center: { lat: 53.5511, lng: 9.9937 },
    zoom: 12,
    searchKeyword: 'Hamburg, Germany',
    size: CitySize.MEDIUM,
  },
  86: {
    cityId: 86,
    cityKo: '상트페테르부르크',
    cityEn: 'SAINTPETERSBURG',
    center: { lat: 59.9311, lng: 30.3609 },
    zoom: 11,
    searchKeyword: 'Saint Petersburg, Russia',
    size: CitySize.MEDIUM,
  },
  88: {
    cityId: 88,
    cityKo: '자그레브',
    cityEn: 'ZAGREB',
    center: { lat: 45.815, lng: 15.9819 },
    zoom: 12,
    searchKeyword: 'Zagreb, Croatia',
    size: CitySize.MEDIUM,
  },
  90: {
    cityId: 90,
    cityKo: '바젤',
    cityEn: 'BASEL',
    center: { lat: 47.5596, lng: 7.5886 },
    zoom: 13,
    searchKeyword: 'Basel, Switzerland',
    size: CitySize.MEDIUM,
  },
  94: {
    cityId: 94,
    cityKo: '안트워프',
    cityEn: 'ANTWERP',
    center: { lat: 51.2194, lng: 4.4025 },
    zoom: 12,
    searchKeyword: 'Antwerp, Belgium',
    size: CitySize.MEDIUM,
  },

  // 동남아시아
  11: {
    cityId: 11,
    cityKo: '방콕',
    cityEn: 'BANGKOK',
    center: { lat: 13.7563, lng: 100.5018 },
    zoom: 12,
    searchKeyword: 'Bangkok, Thailand',
    size: CitySize.MEDIUM,
  },
  14: {
    cityId: 14,
    cityKo: '타이페이',
    cityEn: 'TAIPEI',
    center: { lat: 25.033, lng: 121.5654 },
    zoom: 12,
    searchKeyword: 'Taipei, Taiwan',
    size: CitySize.MEDIUM,
  },
  15: {
    cityId: 15,
    cityKo: '싱가포르',
    cityEn: 'SINGAPORE',
    center: { lat: 1.3521, lng: 103.8198 },
    zoom: 12,
    searchKeyword: 'Singapore',
    size: CitySize.MEDIUM,
  },
  16: {
    cityId: 16,
    cityKo: '다낭',
    cityEn: 'DANANG',
    center: { lat: 16.0544, lng: 108.2022 },
    zoom: 12,
    searchKeyword: 'Da Nang, Vietnam',
    size: CitySize.MEDIUM,
  },
  21: {
    cityId: 21,
    cityKo: '홍콩',
    cityEn: 'HONGKONG',
    center: { lat: 22.3193, lng: 114.1694 },
    zoom: 11,
    searchKeyword: 'Hong Kong',
    size: CitySize.MEDIUM,
  },
  26: {
    cityId: 26,
    cityKo: '나트랑',
    cityEn: 'NHATRANG',
    center: { lat: 12.2388, lng: 109.1967 },
    zoom: 12,
    searchKeyword: 'Nha Trang, Vietnam',
    size: CitySize.MEDIUM,
  },
  37: {
    cityId: 37,
    cityKo: '상하이',
    cityEn: 'SHANGHAI',
    center: { lat: 31.2304, lng: 121.4737 },
    zoom: 11,
    searchKeyword: 'Shanghai, China',
    size: CitySize.MEDIUM,
  },
  38: {
    cityId: 38,
    cityKo: '발리',
    cityEn: 'BALI',
    center: { lat: -8.4095, lng: 115.1889 },
    zoom: 11,
    searchKeyword: 'Bali, Indonesia',
    size: CitySize.MEDIUM,
  },
  43: {
    cityId: 43,
    cityKo: '호치민',
    cityEn: 'HOCHIMINH',
    center: { lat: 10.8231, lng: 106.6297 },
    zoom: 12,
    searchKeyword: 'Ho Chi Minh City, Vietnam',
    size: CitySize.MEDIUM,
  },
  46: {
    cityId: 46,
    cityKo: '하노이',
    cityEn: 'HANOI',
    center: { lat: 21.0285, lng: 105.8542 },
    zoom: 12,
    searchKeyword: 'Hanoi, Vietnam',
    size: CitySize.MEDIUM,
  },
  62: {
    cityId: 62,
    cityKo: '치앙마이',
    cityEn: 'CHIANGMAI',
    center: { lat: 18.7883, lng: 98.9853 },
    zoom: 12,
    searchKeyword: 'Chiang Mai, Thailand',
    size: CitySize.MEDIUM,
  },
  65: {
    cityId: 65,
    cityKo: '베이징',
    cityEn: 'BEIJING',
    center: { lat: 39.9042, lng: 116.4074 },
    zoom: 11,
    searchKeyword: 'Beijing, China',
    size: CitySize.MEDIUM,
  },
  68: {
    cityId: 68,
    cityKo: '가오슝',
    cityEn: 'KAOHSIUNG',
    center: { lat: 22.6273, lng: 120.3014 },
    zoom: 12,
    searchKeyword: 'Kaohsiung, Taiwan',
    size: CitySize.MEDIUM,
  },
  69: {
    cityId: 69,
    cityKo: '쿠알라룸푸르',
    cityEn: 'KUALALUMPUR',
    center: { lat: 3.139, lng: 101.6869 },
    zoom: 12,
    searchKeyword: 'Kuala Lumpur, Malaysia',
    size: CitySize.MEDIUM,
  },
  72: {
    cityId: 72,
    cityKo: '마닐라',
    cityEn: 'MANILA',
    center: { lat: 14.5995, lng: 120.9842 },
    zoom: 12,
    searchKeyword: 'Manila, Philippines',
    size: CitySize.MEDIUM,
  },
  79: {
    cityId: 79,
    cityKo: '타이중',
    cityEn: 'TAICHUNG',
    center: { lat: 24.1477, lng: 120.6736 },
    zoom: 12,
    searchKeyword: 'Taichung, Taiwan',
    size: CitySize.MEDIUM,
  },
  80: {
    cityId: 80,
    cityKo: '블라디보스토크',
    cityEn: 'VLADIVOSTOK',
    center: { lat: 43.1056, lng: 131.8735 },
    zoom: 12,
    searchKeyword: 'Vladivostok, Russia',
    size: CitySize.MEDIUM,
  },
  87: {
    cityId: 87,
    cityKo: '코사무이',
    cityEn: 'KOHSAMUI',
    center: { lat: 9.538, lng: 100.014 },
    zoom: 12,
    searchKeyword: 'Koh Samui, Thailand',
    size: CitySize.MEDIUM,
  },
  89: {
    cityId: 89,
    cityKo: '타이난',
    cityEn: 'TAINAN',
    center: { lat: 22.9999, lng: 120.2269 },
    zoom: 12,
    searchKeyword: 'Tainan, Taiwan',
    size: CitySize.MEDIUM,
  },
  91: {
    cityId: 91,
    cityKo: '프놈펜',
    cityEn: 'PHNOMPENH',
    center: { lat: 11.5564, lng: 104.9282 },
    zoom: 12,
    searchKeyword: 'Phnom Penh, Cambodia',
    size: CitySize.MEDIUM,
  },
  92: {
    cityId: 92,
    cityKo: '타슈켄트',
    cityEn: 'TASHKENT',
    center: { lat: 41.2995, lng: 69.2401 },
    zoom: 12,
    searchKeyword: 'Tashkent, Uzbekistan',
    size: CitySize.MEDIUM,
  },
  93: {
    cityId: 93,
    cityKo: '비엔티안',
    cityEn: 'VIENTIANE',
    center: { lat: 17.9757, lng: 102.6331 },
    zoom: 12,
    searchKeyword: 'Vientiane, Laos',
    size: CitySize.MEDIUM,
  },
  95: {
    cityId: 95,
    cityKo: '텔아비브',
    cityEn: 'TELAVIV',
    center: { lat: 32.0853, lng: 34.7818 },
    zoom: 12,
    searchKeyword: 'Tel Aviv, Israel',
    size: CitySize.MEDIUM,
  },
  96: {
    cityId: 96,
    cityKo: '만달레이',
    cityEn: 'MANDALAY',
    center: { lat: 21.9588, lng: 96.0891 },
    zoom: 12,
    searchKeyword: 'Mandalay, Myanmar',
    size: CitySize.MEDIUM,
  },

  // 북미/오세아니아
  12: {
    cityId: 12,
    cityKo: '뉴욕',
    cityEn: 'NEWYORK',
    center: { lat: 40.7128, lng: -74.006 },
    zoom: 12,
    searchKeyword: 'New York City, USA',
    size: CitySize.EXTRA_LARGE,
  },
  20: {
    cityId: 20,
    cityKo: '하와이',
    cityEn: 'HAWAII',
    center: { lat: 21.3099, lng: -157.8581 },
    zoom: 11,
    searchKeyword: 'Honolulu, Hawaii, USA',
    size: CitySize.EXTRA_LARGE,
  },
  22: {
    cityId: 22,
    cityKo: '시드니',
    cityEn: 'SYDNEY',
    center: { lat: -33.8688, lng: 151.2093 },
    zoom: 12,
    searchKeyword: 'Sydney, Australia',
    size: CitySize.MEDIUM,
  },
  25: {
    cityId: 25,
    cityKo: '괌',
    cityEn: 'GUAM',
    center: { lat: 13.4443, lng: 144.7937 },
    zoom: 11,
    searchKeyword: 'Guam',
    size: CitySize.MEDIUM,
  },
  27: {
    cityId: 27,
    cityKo: '로스앤젤레스',
    cityEn: 'LOSANGELES',
    center: { lat: 34.0522, lng: -118.2437 },
    zoom: 11,
    searchKeyword: 'Los Angeles, USA',
    size: CitySize.EXTRA_LARGE,
  },
  36: {
    cityId: 36,
    cityKo: '샌프란시스코',
    cityEn: 'SANFRANCISCO',
    center: { lat: 37.7749, lng: -122.4194 },
    zoom: 12,
    searchKeyword: 'San Francisco, USA',
    size: CitySize.MEDIUM,
  },
  48: {
    cityId: 48,
    cityKo: '밴쿠버',
    cityEn: 'VANCOUVER',
    center: { lat: 49.2827, lng: -123.1207 },
    zoom: 12,
    searchKeyword: 'Vancouver, Canada',
    size: CitySize.MEDIUM,
  },
  50: {
    cityId: 50,
    cityKo: '멜버른',
    cityEn: 'MELBOURNE',
    center: { lat: -37.8136, lng: 144.9631 },
    zoom: 12,
    searchKeyword: 'Melbourne, Australia',
    size: CitySize.MEDIUM,
  },
  57: {
    cityId: 57,
    cityKo: '토론토',
    cityEn: 'TORONTO',
    center: { lat: 43.6532, lng: -79.3832 },
    zoom: 12,
    searchKeyword: 'Toronto, Canada',
    size: CitySize.MEDIUM,
  },
  61: {
    cityId: 61,
    cityKo: '사이판',
    cityEn: 'SAIPAN',
    center: { lat: 15.2, lng: 145.75 },
    zoom: 12,
    searchKeyword: 'Saipan, Northern Mariana Islands',
    size: CitySize.MEDIUM,
  },
  67: {
    cityId: 67,
    cityKo: '브리즈번',
    cityEn: 'BRISBANE',
    center: { lat: -27.4698, lng: 153.0251 },
    zoom: 12,
    searchKeyword: 'Brisbane, Australia',
    size: CitySize.MEDIUM,
  },
  76: {
    cityId: 76,
    cityKo: '몬트리올',
    cityEn: 'MONTREAL',
    center: { lat: 45.5017, lng: -73.5673 },
    zoom: 12,
    searchKeyword: 'Montreal, Canada',
    size: CitySize.MEDIUM,
  },
};

// 도시 설정 가져오기 함수
export function getCityMapConfig(cityId: number): CityMapConfig | null {
  return cityMapConfigs[cityId] || null;
}

// 기본 설정 (cityId가 없거나 잘못된 경우) - 서울로 설정
export const defaultMapConfig: CityMapConfig = {
  cityId: 6,
  cityKo: '서울',
  cityEn: 'SEOUL',
  center: { lat: 37.5665, lng: 126.978 },
  zoom: 12,
  searchKeyword: 'Seoul, South Korea',
  size: CitySize.LARGE,
};

// 도시 이름으로 설정 찾기 (백업용)
export function getCityMapConfigByName(cityKo: string, cityEn: string): CityMapConfig | null {
  const config = Object.values(cityMapConfigs).find(
    config => config.cityKo === cityKo || config.cityEn.toLowerCase() === cityEn.toLowerCase()
  );
  return config || null;
}

// 지역별 도시 목록 가져오기 (옵션)
export const getCitiesByRegion = () => {
  const regions = {
    korea: Object.values(cityMapConfigs).filter(city =>
      [4, 5, 6, 8, 10, 13, 18, 23, 24, 29, 30, 34, 35, 40, 42, 49, 52, 56, 59, 60, 78].includes(
        city.cityId
      )
    ),
    japan: Object.values(cityMapConfigs).filter(city => [1, 2, 3].includes(city.cityId)),
    europe: Object.values(cityMapConfigs).filter(city =>
      [
        7, 9, 17, 19, 28, 31, 32, 33, 39, 41, 44, 45, 47, 51, 53, 54, 55, 58, 63, 64, 66, 70, 71,
        73, 74, 75, 77, 81, 82, 83, 84, 85, 86, 88, 90, 94,
      ].includes(city.cityId)
    ),
    asia: Object.values(cityMapConfigs).filter(city =>
      [
        11, 14, 15, 16, 21, 26, 37, 38, 43, 46, 62, 65, 68, 69, 72, 79, 80, 87, 89, 91, 92, 93, 95,
        96,
      ].includes(city.cityId)
    ),
    americas: Object.values(cityMapConfigs).filter(city =>
      [12, 20, 22, 25, 27, 36, 48, 50, 57, 61, 67, 76].includes(city.cityId)
    ),
  };

  return regions;
};
