name: Sync on Upstream Update

on:
  repository_dispatch:
    types: [upstream-updated]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/1313BAN/team12-Tlog-FE.git

      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git merge upstream/main --no-edit

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dalsu0222/team12-Tlog-FE.git main
